### ISSUE TITLE
Monitoring of Parameters

### ISSUE THREAD

**Issue by bobbythemoh** [idoodler/MMM-Loxone#1]
Hi, 
It would be nice to be able to monitor data out of loxone.
Examples:
Energy Monitor -->Current Power; Energy Production, Energy Consumption; Counters
Door Status -->Which window / Door is Open
Alarm Status --> ON / OFF
Analog Sensor Values (water cistern distance sensor)

Furthermore, Energy saving for the Montior in "presence mode = ON" would be nice

Thanks

**Comment by idoodler** [comment]
Hi @bobbythemoh 
I realy like the "Alarm Status" idea! I will implement this for sure! I am already looking into, how to add different controls without cluttering the MagicMirror UI.

I am not 100% sure, what you mean with "Energy saving for Monitor in presence mode = ON". Do you mean automatically switching off the MagicMirror after a specific time?

**Comment by idoodler** [comment]
@bobbythemoh Can you please elaborate, what you mean with "Energy saving for Monitor in presence mode = ON"?

**Comment by bobbythemoh** [comment]
Hi, with "presence mode = ON" i mean in the Magic Mirror "config.js" under the configuration for MMM-Loxone "presence: 'true'".
For me this point is resolved because i dont see energy consumption from the monitor if its blacked out.
